spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:sqlserver://127.0.0.1:1433;database=northwind
    username: sa
    password: 12345
    hikari:
      poolName: Hikari
      auto-commit: false
      connectionTimeout: 10000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    format-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.SQLServer2008Dialect
    database: SQL_SERVER
    show-sql: true
    properties:
      hibernate.id.new_generator_mappings: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false

server:
  port: 8080
  servlet:
    contextPath: /api

application:
  api-docs:
    title: NorthWind API
    description: NorthWind API documentation
    version: 0.0.1
    terms-of-service-url:
    contact-name: Localhost
    contact-url: http://localhost.com
    contact-email: contact@local.com
    license: Apache License
    license-url: http://license.localhost.com
    servers:
      - url: http://dev1.localhost.com
        description: dev 1
      - url: http://dev2.localhost.com
        description: dev 2
  cache: # Cache configuration
    caffeine: # Caffeine configuration
      time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache. This sets expireAfterWrite in Caffeine (https://github.com/ben-manes/caffeine/wiki/Eviction#time-based)
      max-entries: 100 # Number of objects in each cache entry
  cors:
    # Enable CORS for angular FE, or tomcat webserver,
    allowed-origins: 'http://localhost:4200,https://localhost'
    # Enable CORS when running app of hti
    allowed-origin-patterns: 'https://*-uat.hti.com.vn'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization'
    allow-credentials: true
    max-age: 1800
  security:
    authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: M2YyMzYyOWZiNjY2NjMzOWZjMzFhMjgxM2NkZjIyY2UxYmQzNGU2MWFkYjc1ZWViMDMxMDgyNTkyNDNmMDcxOTY1N2NlNmFjNjQwYmI3ODkxZDE0Y2VlNjEzN2JhNWEyMjU5NTBlYmJlYWZiZDY4YWU5MTcyNzlkNmQ4ZWY0NDA=
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  http:
    connection-timeout: 10000  # millisecond
    byte-buffer: 30720
    read-timeout: 10  # second
    write-timeout: 10  # second
  logging:
    use-json-format: false # By default, logs are not in Json format

logging:
  config: config/logback.xml
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    com.student.northwind: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "health"
    endpoint:
      health:
        show-details: when_authorized
        roles: 'ROLE_ADMIN'

other-service:
  base-url: http://other-api.com.vn/api

